### ISSUE TITLE
Serve static files without using express

### ISSUE THREAD

**Issue by daquinoaldo** [daquinoaldo/https-localhost#29]
Rewrite the `app.serve` function at [row 61 in index.js](https://github.com/daquinoaldo/https-localhost/blob/master/index.js#L61) so that will serve static files without using express.js.

You'll be mentioned as a contributor.
Happy [Hacktoberfest](https://hacktoberfest.digitalocean.com)!

**Comment by prkhrv** [comment]
Can use Node-Static?

**Comment by HeyIts-RJ** [comment]
Hello, I try to resolve your issue by using the native file system module not express. Please check it and merge it if it is right.

Here is my methodology to implementation
`var fs = require('fs'),
    http = require('http');

http.createServer(function (req, res) {
  fs.readFile(__dirname + req.url, function (err,data) {
    if (err) {
      res.writeHead(404);
      res.end(JSON.stringify(err));
      return;
    }
    res.writeHead(200);
    res.end(data);
  });
}).listen(8080);`

**Comment by daquinoaldo** [comment]
@prkhrv I would like to remove as many dependencies as possible from my package. `node-static` is pretty lightweight, but I prefer a native solution if it is possible.

Actually, I prefer @HeyIts-RJ's solution. I have to review the code with more attention, probably this evening (CET timezone).
Could you please fix the linter errors, so that I can better test it? Give a look to the GitHub Actions CI or just run `npm t` on your fork.
Also, even if its a developer tool, `JSON.stringify(err)` could probably be rewritten in a more user-friendly way.

**Comment by HeyIts-RJ** [comment]
Alright @daquinoaldo I will fix the linter error and actually I'm thinking to remove `JSON.stringify(err)`

**Comment by HeyIts-RJ** [comment]
@daquinoaldo I fixed the linter errors and warning in my last commit.

**Comment by daquinoaldo** [comment]
@HeyIts-RJ take a look at my comment on #30. Can you implement it?
If you think it is too complex we can use `node-static` as suggested by @prkhrv.

**Comment by HeyIts-RJ** [comment]
Give me some time to try it.

**Comment by HeyIts-RJ** [comment]
Give me some time for it @daquinoaldo I think I'm moving in right direction.

**Comment by daquinoaldo** [comment]
Sure, no problem

**Comment by daquinoaldo** [comment]
Someone wants to help @HeyIts-RJ with #30 or whish to propose its own solution?

**Comment by HeyIts-RJ** [comment]
> Someone wants to help @HeyIts-RJ with #30 or whish to propose its own solution?

Alright. It's open for that.
