### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by angelcnsk** [daquinoaldo/https-localhost#31]
**Bug description**
Hi, I'm trying to npm run serve once the https-localhost dependency is installed to use ssl and it sends me the following compilation error message.

```
Failed to compile.

./node_modules/https-localhost/index.js 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/usr/bin/env node
| 
| const path = require("path")
```

I put the following lines in my js file, I tried to find information about it but I can't solve the problem, I appreciate any possible help.

```
const app = require("https-localhost")()
// app is an express app, do what you usually do with express
app.listen(port)
```

**System information (please complete the following information):**
 - OS: MacOS X Mojave
 - App version 4.4.0

**Comment by daquinoaldo** [comment]
Hi @angelcnsk!
- Which version of Node.js are you using? You can find it with `node --version`.
- Are you running the script standalone from command line (i.e. `serve my-folder`) or are you using as module (e.g. `const app = require("https-localhost")()`)?

**Comment by rzfzr** [comment]
@daquinoaldo Greetings!
can you reopen the issue? It is still relevant, I'm encountering this.
node v16.16.0
using it as a module in an electron/vuejs app
I've used it in non-vue electron/ts app, so I believe it is something in the loader.
@angelcnsk did you solve it?

**Comment by rzfzr** [comment]
Trying to remove the line gives this, is it looking for certs.js in the wrong place?
![image](https://user-images.githubusercontent.com/13456224/196009788-9ac9593a-e3e4-4c6b-8982-b3b9695e9b68.png)
Have failed to use a shebang loader

**Comment by daquinoaldo** [comment]
@rzfzr, can you try removing the shebang line from all the files and importing a local version of the module without shebangs? If it works, please open a pull request.

**Comment by wll8** [comment]
Since you are running `npm run serve`, you are consuming a web service. So you can put the following code in the browser runtime environment.

You can try to place the code for the node environment in vue.config.js.
