### ISSUE TITLE
Support for ARM architecture (Raspberry Pi 3 B)

### ISSUE THREAD

**Issue by rsip22** [daquinoaldo/https-localhost#37]
**How would you like to expand the functionalities?**
Currently, it's not possible to use this package on ARM devices, because the code reads only the platform "linux" and it assumes it should just pull and run the linux-amd64 mkcert binary. 

**Are there alternatives?**
mkcert already provides a [binary to run on linux-arm devices](https://github.com/FiloSottile/mkcert/releases).

**Is it a breaking change?**
Not that I am aware of.

I have already fixed this locally and I have successfully tested the code on Raspberry Pi 3 B. I am creating this issue to report on it and as a basis for opening a Pull Request with this improvement, if that's okay.

**Comment by daquinoaldo** [comment]
Hi @rsip22, thank you for you interest and for reporting this bug!

I'll be happy to support also ARM devices. A would appreciate a lot if you are able to open a pull request, I'll handle it on Monday.

Please remember to run `npm t` to test your edits.

**Comment by rsip22** [comment]
Thank you for being open about this (and for sharing the code), @daquinoaldo ! 

I am not familiar with Github Actions, so even though I made the code work here (and the tests pass), I was not very successful in my attempt to add testing for ARM to the CI... any suggestions regarding this?

**Comment by daquinoaldo** [comment]
Wow, super fast!
I don't have my laptop at hand now, so I'll approve Monday when I can publish the new version on npm.
Don't worry about GitHub CI, I'll add the configuration by myself.
Thank you for your effort!

**Comment by Dreamer-Paul** [comment]
My Mac Mini (M1 Chip) has a problem like this, I wonder you will fix it? @daquinoaldo 

```
Error: Command failed: /Users/xinda/Library/Application\ Support/https-localhost/mkcert-v1.4.3-darwin-amd64 -install -cert-file /Users/xinda/Library/Application\ Support/https-localhost/localhost.crt -key-file /Users/xinda/Library/Application\ Support/https-localhost/localhost.key localhost
/bin/sh: /Users/xinda/Library/Application Support/https-localhost/mkcert-v1.4.3-darwin-amd64: Bad CPU type in executable
```
