### ISSUE TITLE
Problems with SPA routing

### ISSUE THREAD

**Issue by gstvribs** [daquinoaldo/https-localhost#39]
Hi, i'm having two issues with this lib when i'm trying to serve my react spa.

The first is: when i access directly a route work well, but when i try to do a refresh the lib just got lost and i receive a 404 (saying Forbidden 403 from rs.sendFile message)
The second is: when i access directly the i receive a Forbidden from node.js file system, because relative are suspicious to node.

i'm working on a PR for this issue.

**Comment by daquinoaldo** [comment]
Hi @gstvribs, thank you for your feedback.
I've reviewed your PR: it's clear, clean, and effective. I have finally understood the problem previously described in #36.

I'll merge the PR, as well as publish the new version on npm, as soon as I have some free time, in this days.

**Comment by daquinoaldo** [comment]
Code tested and PR merged. Let me know if you are interested in working at #36. In that case, I would like to include also that PR in the next version on npm, otherwise I'll push these new changes.

Thank you very much again for your effort!

**Comment by gstvribs** [comment]
Nice!

@daquinoaldo, now with these changes merged, the lib now supports SPA routes by default and static websites, i think #36 could be closed.

The ideia in the beginning is to add a flag, but, with this PR merged, https-localhost now support spa by default.

Me and @thiagones work on the same project, with this code already merge I think it’s good to go :)

**Comment by daquinoaldo** [comment]
Okay, perfect. Thank you, good luck with your project!
