### ISSUE TITLE
Running mkcert to generate certificates Fail

### ISSUE THREAD

**Issue by giangldo** [daquinoaldo/https-localhost#42]
**Bug description**
I hit an error that can not install the mkcert on window 10
Error: The process cannot access the file because it is being used by another process.

**To Reproduce**
`import https from 'https';
import httpsLocalhost from 'https-localhost';
import app from './app';

const port = process.env.PORT || 8000;

(async () => {
  try {
    const certs = await httpsLocalhost().getCerts();
    const server = https.createServer(certs, app);
    server.listen(port, () => {
      console.log(`NODE_ENV : ${process.env.NODE_ENV}`);
      console.log(`Server started at https://localhost:${port}`);
    });
  } catch (error) {
    console.log(error);
  }
})();`

**System information (please complete the following information):**
 - OS: Windows 10 Pro - v1909
 - Express Server - 4.17.1
- Node - v11.6.0

**Additional context**
Thank you very much.

**Comment by daquinoaldo** [comment]
Hi @giangldo, thank you for your reporting.

I'm not able to reproduce the bug.
Are you able to run a debugger against the code to provide the stack trace or the line that causes this error?

Also, have you tried to run once the tool in an elevated shell? The first run of the tool generates the certificates, sometimes this operation needs to execute the PowerShell as administrator. Next runs will find the existent certificates and can be run as user.

Let me know.

**Comment by giangldo** [comment]
Hi daquinoaldo,

you are right. run it second time and it works. 

thank you for pointing that out.

...best

**Comment by daquinoaldo** [comment]
I'm glad your problem is solved.
Regards
