### ISSUE TITLE
不安全连接问题

### ISSUE THREAD

**Issue by formattedzzz** [daquinoaldo/https-localhost#43]
有没有同学用了这个包之后 某些网站会出现 **暂时性** 访问不了的情况 提示如下

> 您的连接不是私密连接，攻击者可能会试图从 github.com 窃取您的信息

遇到的出现问题的站点：
- github 官网
- https://lavas-project.github.io/pwa-book/chapter01/6-your-first-pwa.html

难道是生成的证书有问题？

**Comment by daquinoaldo** [comment]
Hi @formattedzzz,
can you please explain better in English? I used a translator but it is not clear what you are meaning.
Have you some difficulties in visiting that site or when serving the PWA built with that tutorial you are experiencing that issue on localhost?

**Comment by formattedzzz** [comment]
> Hi @formattedzzz,
> can you please explain better in English? I used a translator but it is not clear what you are meaning.
> Have you some difficulties in visiting that site or when serving the PWA built with that tutorial you are experiencing the issue on localhost?

aha! sorry.  maybe it's not a  specific problem.  at the first running, when i generator the mkcert and open the safari by the same ip, the safari prompt me some potiential dangerous about localhost cert and ask for authorization. I guess maybe the point result in i can't access some website temporary(about few hours at the same appid), such as github.com or xxx.github.io which is strict about security.

**Comment by daquinoaldo** [comment]
This is strange... For which domain have you generate the certificate? localhost or custom domain?

**Comment by formattedzzz** [comment]
localhost

**Comment by daquinoaldo** [comment]
That is pretty unusual, seems something unrelated...
Let me know if you experience this problem again.

**Comment by formattedzzz** [comment]
Good luck no emersion...
