### ISSUE TITLE
Automated Certificate Management - Heroku

### ISSUE THREAD

**Issue by dschinkel** [daquinoaldo/https-localhost#45]
n00b here.  How does this work if I've got a dyno running via Heroku and I've setup my dyno to manage my certifications?

https://devcenter.heroku.com/articles/automated-certificate-management and I've set that up for Heroku to get the cert from https://letsencrypt.org

Just trying to understand how https-localhost is able to pick up the automated certificate management in all this or does it not even care about that?  Because in your readme you talk about creating certs locally which I do not do myself, https://letsencrypt.org/ does it.

**Comment by daquinoaldo** [comment]
Hi @dschinkel,
I designed https-localhost to run... well, on localhost 😅
I'm not sure I understand correctly, but it seems to me that you want to use it to serve pages using Heroku, right?
You can't use your own certificate with https-localhost, even if will I'm evaluating this functionality for the future.

To serve file with Heroku, I can suggest you [Zeit's serve](https://www.npmjs.com/package/serve): it serves only on http connection, but if I remember well, Heroku provide https also for your http server, by default, proxying requests in some way.
If you need a custom server, to provide APIs or other functionality different from just serve static files, or simply to have an advanced configuration, take a look to my [index.js](https://github.com/daquinoaldo/https-localhost/blob/43b06c1d80f38afacb53c882d5e85b287148f4a8/index.js) file. You can build your own server using this structure. At [row 35](https://github.com/daquinoaldo/https-localhost/blob/43b06c1d80f38afacb53c882d5e85b287148f4a8/index.js#L25) replace `await getCerts(domain)` with an object of this form:
```js
{
  key: fs.readFileSync("certificate.key"),
  cert: fs.readFileSync("certificate.crt")
}
```

I never tried the certificate management, but I've used Heroku before and I always provided an http server, delegating totally the TLS to Heroku.
I recently deployed [this server](https://github.com/daquinoaldo/nodejs-codelab/tree/master/6-server-solution) to [bookmarks-notes.herokuapp.com](https://bookmarks-notes.herokuapp.com). As you can see, the connection is https.
