### ISSUE TITLE
Bug: Intermediate CA not added? Thanks for this module!

### ISSUE THREAD

**Issue by DTrejo** [daquinoaldo/https-localhost#48]
Thanks for this module!

**Bug description**
openssl and `https.get` are unable to verify the first certificate () when making a request to a local server created with https-localhost.

**To Reproduce**
1. Start an https-localhost server on localhost:443 with `npx https-localhost`
2. Run `openssl s_client -connect localhost:443` -> you will see:
  ```
CONNECTED(00000005)
depth=0 O = mkcert development certificate, OU = david@davids-mbp.lan
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 O = mkcert development certificate, OU = david@davids-mbp.lan
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/O=mkcert development certificate/OU=david@davids-mbp.lan
   i:/O=mkcert development CA/OU=david@davids-mbp.lan/CN=mkcert david@davids-mbp.lan
---
Server certificate
```
3. Or, make a request using `https.get`

```js
const https = require('https')
https.get('https://localhost/', (res) => {
        console.log('statusCode:', res.statusCode)
        console.log('headers:', res.headers)

        res.on('data', (d) => {
            process.stdout.write(d)
        })
    }).on('error', (e) => {
        console.error(e)
    })
```

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1492:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:935:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:693:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

**Expected behavior**
The request(s) succeed and are trusted. Based on my googling`*`, I believe the intermediate CA needs to be returned from the https-localhost server. I did try adding the `.crt` file to my keychain, and I trusted it, and this error still happens.

`*`: 1) https://stackoverflow.com/questions/19665863/how-do-i-use-a-self-signed-certificate-for-a-https-node-js-server 2) https://thequietinnovator.com/2015/10/11/how-to-fix-nodejs-cert_untrusted-issues/ 

**System information (please complete the following information):**
 - OS: MacOS X Catalina 10.5.4
 - App version 4.5.3

**Additional context**
I think this would be in scope for this module to handle, right? If not, no worries. Another thought... what if https-localhost created a private letsencrypt cert?

Thanks for your hard work on this module!
D

**Comment by daquinoaldo** [comment]
Hi @DTrejo,
thank you for the feedback!

It is not possible to use Let's Encrypt because it runs on localhost. You'll need to buy a domain and expose your device on Internet to allow Let's Encrypt to verify your server and produce the certificate.

Far what concern the bug you are experiencing: the connection should be verified, it is the aim of this module.
Have you tried to use a browser? The connection is trusted or not?

**Comment by DTrejo** [comment]
The project did work great in the browser, no problems. I ended up using https://github.com/jsha/minica to create a cert, then I started my server like this so that HTTPS requests from node programs would work: 

```sh
NODE_EXTRA_CA_CERTS='./https/minica.pem' node dev-server.js
```
