### ISSUE TITLE
Unable to configure CORS

### ISSUE THREAD

**Issue by josencv** [daquinoaldo/https-localhost#50]
**Bug description**
Cannot configure CORS to return specific origins in preflight response headers, because it's handled by the library, which automatically returns wildcards. It is a problem because there are some cases in which browsers reject wildcards due to security reasons.

My specific case is trying to make XHR requests with the `withCredentials` flag set to `true`, which fails as documented [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Requests_with_credentials).

This problem was introduced in version 4.6.0, specifically in #47. If I use version 4.5.1, it works fine, because the preflight requests reaches my app's CORS middleware.

**To Reproduce**
1. Run an express server with https-localhost
2. Make an XHR request with `withCredentials` set to `true` with a modern browser

**Expected behavior**
1. The request should fail because no Access-Control-Allow-Origin was set, not because a wildcard was sent.

If you still want the library to allow any origin easily, maybe add an option when initializing the server at least, so the programmer knows that it's enabling it, at its own risk

**System information:**
- OS: macOS 10.5.5 (Catalina) 
- App version: 4.6.0
- Node version: 13.3.0
- Chrome 84.0.4147.135 (Official Build) (64-bit)

Thanks!

**Comment by daquinoaldo** [comment]
Thank you for the feedback. I'll add a flag as suggested.
