### ISSUE TITLE
Running on Mac as a non-admin user

### ISSUE THREAD

**Issue by Kore-Development** [daquinoaldo/https-localhost#52]
**Bug description**
When running on a Mac as a non-admin user it asks for a sudo password then says I'm not in the sudoers file (because I'm not admin). I installed mkcert normally and ran mkcert -install. Could there be a flag for when you already have mkcert installed or something?

**To Reproduce**
1. Run as non-admin user on Mac

**Expected behavior**
Not ask for sudo password

**System information (please complete the following information):**
 - OS: MacOS X Catalina 10.15.7 (I would update to Big Sur but I have a mid-2014 Macbook so updating is disabled for now)
 - App version [e.g. 1.1.2]: Just installed today, so I guess it's latest

**Additional context**

**Comment by daquinoaldo** [comment]
Hi! Thank you for your feedback.
Unfortunately it assumes you have super user permissions (just the first time). It was a problem due to mkcert. This weekend I’m going to upgrade mkcert to the latest version, it should solve the problem according to what you said.
I’ll keep you updated!

**Comment by daquinoaldo** [comment]
Hi @Kore-Development,
[v4.6.4](https://github.com/daquinoaldo/https-localhost/releases/tag/v4.6.4) is out and is already published on npm.
Let me know if it solves the issue. Consider that `https-localhost` does not require root permission. So if it asks for sudo password it's `mkcert`, as stated in these [release notes](https://github.com/FiloSottile/mkcert/releases/tag/v1.4.1).
