### ISSUE TITLE
detected as the virus on windows

### ISSUE THREAD

**Issue by murunwas** [daquinoaldo/https-localhost#54]
![ScreenShot_20201213213305](https://user-images.githubusercontent.com/8838943/102021883-b9b00080-3d8b-11eb-9251-3de0981acf10.png)

**Comment by daquinoaldo** [comment]
This is a false positive. `mkcert` is a tool to generate and trust certificates. It’s open source, you can check it on [mkcert.dev](https://mkcert.dev).
