### ISSUE TITLE
JAVA_HOME Set on Windows, Fails (access denied)

### ISSUE THREAD

**Issue by carsenk** [daquinoaldo/https-localhost#56]
**Bug description**
https://puu.sh/H4RuS/03a83a5e5b.png

**Expected behavior**
Got the mkcert popup to install the cert, but then it try keyimport or something after which it fails due to JAVA_HOME being set maybe? Access denied in the jdk folder? I tried removing JAVA_HOME from my enviroment variables and restarting and trying again, still same problem

**System information (please complete the following information):**
Windows 10
Latest Version

**Comment by daquinoaldo** [comment]
Hi @carsenk,
unfortunately the output is truncated in the image you pasted.
Anyway, the error seems to be related to Java has you said. Have you tried to run the script with `serve`? It could work anyway.
If it doesn’t work, you can try to run it again in an elevated shell (you have to run Powershell as an administrator). The error seems to be related to missing permissions, that shouldn’t be a problem when running as admin.
Let me know if it works, and thank you for reach me out!
