### ISSUE TITLE
create a certificate for additional domains does not work

### ISSUE THREAD

**Issue by Gintez** [daquinoaldo/https-localhost#59]
I want to add certificate to additional domains. I add:
`const httpsLocalhost = require('https-localhost')('myDomain.com');`

But certificates for localhost only are created:
![Screen Shot 2021-03-23 at 15 00 13](https://user-images.githubusercontent.com/20800867/112150192-7cf47080-8be8-11eb-8b8a-468fe315824b.png)

![Screen Shot 2021-03-23 at 14 59 38](https://user-images.githubusercontent.com/20800867/112150118-69490a00-8be8-11eb-9c4c-9c7befe68e39.png)

**Comment by daquinoaldo** [comment]
The code seems correct to me. Which version are you using?
Keep in mind that the server will serve your content on localhost, hence it’s up to you to make your domain pointing localhost (either via DNS or changing system records).

**Comment by Gintez** [comment]
I am using "https-localhost": "^4.6.4";
The localhost using https works fine, but there are no certificates generated for the 'myDomain.com', I would expect that if `const httpsLocalhost = require('https-localhost')('myDomain.com');` then I would get the cert and key generated for the myDomain.com as well. Am I wrong here?

**Comment by daquinoaldo** [comment]
Hi @Gintez,
Sorry for the late answer.
I just tested it and it works correctly. Here how I tested it.

`$ cat test.js`
```js
const httpsLocalhost = require('https-localhost')('myDomain.com');
httpsLocalhost.serve()
```
Note that `.serve()` starts the server.

`$ sudo node test.js`
```
Serving static path: /workspaces/test
Generating certificates...
Certificates path: /home/codespace/.config/https-localhost. Never modify nor share this files.
Downloading the mkcert executable...
Running mkcert to generate certificates...
Created a new local CA 💥
The local CA is now installed in the system trust store! ⚡️
The local CA is now installed in Java's trust store! ☕️


Created a new certificate valid for the following names 📜
 - "myDomain.com"

The certificate is at "/home/codespace/.config/https-localhost/myDomain.com.crt" and the key at "/home/codespace/.config/https-localhost/myDomain.com.key" ✅

It will expire on 30 July 2023 🗓


Certificates generated, installed and trusted. Ready to go!
Server running on port 443.
```
