### ISSUE TITLE
https server not working with socket.io

### ISSUE THREAD

**Issue by neryash** [daquinoaldo/https-localhost#62]
**Bug description**
Socket.io isn't running with this server.

**To Reproduce**
try using socket.io with the library

**Expected behavior**
the websocket should receive messages, but doesn't

**System information (please complete the following information):**
 - OS: Windows 10 20H2 19042.928
 - App version 4.6.4

**Comment by daquinoaldo** [comment]
Hi @neryash,
I've never used Socket.io, and unfortunately, I don't have time to allocate on this project currently.
If you can open a pull request, I'll be super happy to review it and merge it.
Otherwise, can you please provide a code that I can run to test it? I'll try as soon as I can.
