### ISSUE TITLE
Http

### ISSUE THREAD

**Issue by Holokong** [daquinoaldo/https-localhost#96]
**How would you like to expand the functionalities?**
A description of what the new feature aim should be.

**Are there alternatives?**
Workaround, etc...

**Is it a breaking change?**
It changes how the users interact with this tool?

**Comment by daquinoaldo** [comment]
Hello mate 👋

Thank you for opening this issue.
Unfortunately, it's a bit vague as it seems you didn't fill in the placeholder description.
From the title, it looks like you would appreciate http support. However, this is outside this project's scope. There is plenty of http servers, and my go-to choice when for quick static file serving is `serve`.
Hope this helps!
